services:
  - type: web
    name: yot-tickets-api
    runtime: node
    rootDir: apps/api
    buildCommand: npm install && npx prisma generate && npx nest build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
