services:
  - type: web
    name: yot-tickets-api
    runtime: node
    buildCommand: bash render-build.sh
    startCommand: node apps/api/dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
